/**
 * WASM Core Module Exports
 *
 * This module provides TypeScript bindings for the Rust WASM core.
 * All cryptographic operations are performed in WebAssembly for security and performance.
 */

// Import the WASM module (will be generated by wasm-pack)
// @ts-ignore - WASM module will be generated during build
import * as wasm from './pkg/local_wallet_vault_core';

export interface CreateVaultResult {
  metadata: string; // JSON string
  wrappedKeys: string; // JSON string
  manifest: string; // JSON string
  vault: string; // JSON string
  dek: Uint8Array;
}

export interface UnlockVaultResult {
  vault: string; // JSON string
  dek: Uint8Array;
}

export interface EnvelopeResult {
  ciphertext: Uint8Array;
  nonce: Uint8Array;
}

/**
 * Initialize the WASM module
 */
export async function init(): Promise<void> {
  await wasm.default();
  wasm.wasm_init();
}

/**
 * Get the WASM module version
 */
export function getVersion(): string {
  return wasm.wasm_version();
}

// ============================================================================
// Base64URL Functions
// ============================================================================

/**
 * Encode bytes to base64url string
 */
export function base64urlEncode(data: Uint8Array): string {
  return wasm.wasm_base64url_encode(data);
}

/**
 * Decode base64url string to bytes
 */
export function base64urlDecode(s: string): Uint8Array {
  return wasm.wasm_base64url_decode(s);
}

/**
 * Generate random bytes
 */
export function generateRandomBytes(length: number): Uint8Array {
  return wasm.wasm_generate_random_bytes(length);
}

/**
 * Generate random base64url string
 */
export function generateRandomBase64url(length: number): string {
  return wasm.wasm_generate_random_base64url(length);
}

// ============================================================================
// Crypto Functions
// ============================================================================

/**
 * Generate a new AES-256 key
 */
export function generateAESKey(): Uint8Array {
  return wasm.wasm_generate_aes_key();
}

/**
 * Encrypt data using AES-GCM-256
 */
export function encryptAESGCM(key: Uint8Array, plaintext: Uint8Array, aad: Uint8Array): EnvelopeResult {
  const result = wasm.wasm_encrypt_aes_gcm(key, plaintext, aad);
  return {
    ciphertext: result.ciphertext,
    nonce: result.nonce,
  };
}

/**
 * Decrypt data using AES-GCM-256
 */
export function decryptAESGCM(key: Uint8Array, ciphertext: Uint8Array, nonce: Uint8Array, aad: Uint8Array): Uint8Array {
  return wasm.wasm_decrypt_aes_gcm(key, ciphertext, nonce, aad);
}

/**
 * Derive key using HKDF-SHA-256
 */
export function deriveKeyHKDF(ikm: Uint8Array, salt: Uint8Array, info: string, length: number): Uint8Array {
  return wasm.wasm_derive_key_hkdf(ikm, salt, info, length);
}

/**
 * Derive KEK from PRF output
 */
export function deriveKEKFromPRF(prfOutput: Uint8Array): Uint8Array {
  return wasm.wasm_derive_kek_from_prf(prfOutput);
}

// ============================================================================
// Key Wrap Functions
// ============================================================================

/**
 * Wrap DEK with KEK
 */
export function wrapDEK(kek: Uint8Array, dek: Uint8Array, vaultId: string): string {
  return wasm.wasm_wrap_dek(kek, dek, vaultId);
}

/**
 * Unwrap DEK with KEK
 */
export function unwrapDEK(kek: Uint8Array, envelopeJson: string): Uint8Array {
  return wasm.wasm_unwrap_dek(kek, envelopeJson);
}

// ============================================================================
// Envelope Functions
// ============================================================================

/**
 * Create an envelope for encrypted data
 */
export function createEnvelope(key: Uint8Array, plaintext: Uint8Array, vaultId: string, purpose: 'dek-wrap' | 'manifest' | 'wallet-record' | 'backup'): string {
  return wasm.wasm_create_envelope(key, plaintext, vaultId, purpose);
}

/**
 * Decrypt an envelope
 */
export function decryptEnvelope(key: Uint8Array, envelopeJson: string): Uint8Array {
  return wasm.wasm_decrypt_envelope(key, envelopeJson);
}

// ============================================================================
// Vault Functions
// ============================================================================

/**
 * Create a new vault
 */
export function createVault(prfOutput: Uint8Array, credentialId: string, userHandle: string): CreateVaultResult {
  const result = wasm.wasm_create_vault(prfOutput, credentialId, userHandle);
  return {
    metadata: result.metadata,
    wrappedKeys: result.wrappedKeys,
    manifest: result.manifest,
    vault: result.vault,
    dek: result.dek,
  };
}

/**
 * Unlock a vault
 */
export function unlockVault(prfOutput: Uint8Array, metadataJson: string, wrappedKeysJson: string, manifestJson: string): UnlockVaultResult {
  const result = wasm.wasm_unlock_vault(prfOutput, metadataJson, wrappedKeysJson, manifestJson);
  return {
    vault: result.vault,
    dek: result.dek,
  };
}

/**
 * Encrypt a wallet record
 */
export function encryptRecord(dek: Uint8Array, plaintext: Uint8Array, vaultId: string, recordId: string): string {
  return wasm.wasm_encrypt_record(dek, plaintext, vaultId, recordId);
}

/**
 * Decrypt a wallet record
 */
export function decryptRecord(dek: Uint8Array, recordJson: string): Uint8Array {
  return wasm.wasm_decrypt_record(dek, recordJson);
}

// Re-export types
export * from './types';