/**
 * WASM Core Module Exports
 *
 * This module provides TypeScript bindings for the Rust WASM core.
 * All cryptographic operations are performed in WebAssembly for security and performance.
 */

// Import the WASM module (will be generated by wasm-pack)
// @ts-ignore - WASM module will be generated during build
import * as wasmModule from './pkg/local_wallet_vault_core';

export interface CreateVaultResult {
  metadata: string; // JSON string
  wrappedKeys: string; // JSON string
  manifest: string; // JSON string
  vault: string; // JSON string
  dek: Uint8Array;
}

export interface UnlockVaultResult {
  vault: string; // JSON string
  dek: Uint8Array;
}

export interface EnvelopeResult {
  ciphertext: Uint8Array;
  nonce: Uint8Array;
}

// Track initialization state
let initialized = false;
let initPromise: Promise<void> | null = null;

/**
 * Initialize the WASM module
 * Must be called before any other functions
 */
export async function init(): Promise<void> {
  if (initialized) return;
  
  // If initialization is in progress, wait for it
  if (initPromise) {
    return initPromise;
  }
  
  initPromise = (async () => {
    // @ts-ignore - default export is the init function
    await wasmModule.default();
    // @ts-ignore - wasm_init sets up panic hook for better error messages
    wasmModule.wasm_init();
    initialized = true;
  })();
  
  return initPromise;
}

/**
 * Check if WASM module is initialized
 */
export function isInitialized(): boolean {
  return initialized;
}

/**
 * Assert that the WASM module is initialized
 */
function assertInitialized(): void {
  if (!initialized) {
    throw new Error('WASM module not initialized. Call init() first.');
  }
}

/**
 * Get the WASM module version
 */
export function getVersion(): string {
  assertInitialized();
  // @ts-ignore - wasm_version is exported after init
  return wasmModule.wasm_version();
}

// ============================================================================
// Base64URL Functions
// ============================================================================

/**
 * Encode bytes to base64url string
 */
export function base64urlEncode(data: Uint8Array): string {
  assertInitialized();
  // @ts-ignore - function is available after init
  return wasmModule.wasm_base64url_encode(data);
}

/**
 * Decode base64url string to bytes
 */
export function base64urlDecode(s: string): Uint8Array {
  assertInitialized();
  // @ts-ignore - function is available after init
  return wasmModule.wasm_base64url_decode(s);
}

/**
 * Generate random bytes
 */
export function generateRandomBytes(length: number): Uint8Array {
  assertInitialized();
  // @ts-ignore - function is available after init
  return wasmModule.wasm_generate_random_bytes(length);
}

/**
 * Generate random base64url string
 */
export function generateRandomBase64url(length: number): string {
  assertInitialized();
  // @ts-ignore - function is available after init
  return wasmModule.wasm_generate_random_base64url(length);
}

// ============================================================================
// Crypto Functions
// ============================================================================

/**
 * Generate a new AES-256 key
 */
export function generateAESKey(): Uint8Array {
  assertInitialized();
  // @ts-ignore - function is available after init
  return wasmModule.wasm_generate_aes_key();
}

/**
 * Encrypt data using AES-GCM-256
 */
export function encryptAESGCM(key: Uint8Array, plaintext: Uint8Array, aad: Uint8Array): EnvelopeResult {
  assertInitialized();
  // @ts-ignore - function is available after init
  const result = wasmModule.wasm_encrypt_aes_gcm(key, plaintext, aad);
  return {
    ciphertext: result.ciphertext,
    nonce: result.nonce,
  };
}

/**
 * Decrypt data using AES-GCM-256
 */
export function decryptAESGCM(key: Uint8Array, ciphertext: Uint8Array, nonce: Uint8Array, aad: Uint8Array): Uint8Array {
  assertInitialized();
  // @ts-ignore - function is available after init
  return wasmModule.wasm_decrypt_aes_gcm(key, ciphertext, nonce, aad);
}

/**
 * Derive key using HKDF-SHA-256
 */
export function deriveKeyHKDF(ikm: Uint8Array, salt: Uint8Array, info: string, length: number): Uint8Array {
  assertInitialized();
  // @ts-ignore - function is available after init
  return wasmModule.wasm_derive_key_hkdf(ikm, salt, info, length);
}

/**
 * Derive KEK from PRF output
 */
export function deriveKEKFromPRF(prfOutput: Uint8Array): Uint8Array {
  assertInitialized();
  // @ts-ignore - function is available after init
  return wasmModule.wasm_derive_kek_from_prf(prfOutput);
}

// ============================================================================
// Key Wrap Functions
// ============================================================================

/**
 * Wrap DEK with KEK
 */
export function wrapDEK(kek: Uint8Array, dek: Uint8Array, vaultId: string): string {
  assertInitialized();
  // @ts-ignore - function is available after init
  return wasmModule.wasm_wrap_dek(kek, dek, vaultId);
}

/**
 * Unwrap DEK with KEK
 */
export function unwrapDEK(kek: Uint8Array, envelopeJson: string): Uint8Array {
  assertInitialized();
  // @ts-ignore - function is available after init
  return wasmModule.wasm_unwrap_dek(kek, envelopeJson);
}

// ============================================================================
// Envelope Functions
// ============================================================================

/**
 * Create an envelope for encrypted data
 */
export function createEnvelope(key: Uint8Array, plaintext: Uint8Array, vaultId: string, purpose: 'dek-wrap' | 'manifest' | 'wallet-record' | 'backup'): string {
  assertInitialized();
  // @ts-ignore - function is available after init
  return wasmModule.wasm_create_envelope(key, plaintext, vaultId, purpose);
}

/**
 * Decrypt an envelope
 */
export function decryptEnvelope(key: Uint8Array, envelopeJson: string): Uint8Array {
  assertInitialized();
  // @ts-ignore - function is available after init
  return wasmModule.wasm_decrypt_envelope(key, envelopeJson);
}

// ============================================================================
// Vault Functions
// ============================================================================

/**
 * Create a new vault
 * @param prfOutput - PRF output from WebAuthn (32 bytes)
 * @param prfSalt - PRF salt used for key derivation (base64url)
 * @param credentialId - WebAuthn credential ID (base64url)
 * @param userHandle - WebAuthn user handle (base64url)
 * @param createdAt - ISO 8601 timestamp (from JavaScript's new Date().toISOString())
 */
export function createVault(prfOutput: Uint8Array, prfSalt: string, credentialId: string, userHandle: string, createdAt: string): CreateVaultResult {
  assertInitialized();
  // @ts-ignore - function is available after init
  const result = wasmModule.wasm_create_vault(prfOutput, prfSalt, credentialId, userHandle, createdAt);
  return {
    metadata: result.metadata,
    wrappedKeys: result.wrappedKeys,
    manifest: result.manifest,
    vault: result.vault,
    dek: result.dek,
  };
}

/**
 * Unlock a vault
 */
export function unlockVault(prfOutput: Uint8Array, metadataJson: string, wrappedKeysJson: string, manifestJson: string): UnlockVaultResult {
  assertInitialized();
  // @ts-ignore - function is available after init
  const result = wasmModule.wasm_unlock_vault(prfOutput, metadataJson, wrappedKeysJson, manifestJson);
  return {
    vault: result.vault,
    dek: result.dek,
  };
}

/**
 * Encrypt a wallet record
 */
export function encryptRecord(dek: Uint8Array, plaintext: Uint8Array, vaultId: string, recordId: string): string {
  assertInitialized();
  // @ts-ignore - function is available after init
  return wasmModule.wasm_encrypt_record(dek, plaintext, vaultId, recordId);
}

/**
 * Decrypt a wallet record
 */
export function decryptRecord(dek: Uint8Array, recordJson: string): Uint8Array {
  assertInitialized();
  // @ts-ignore - function is available after init
  return wasmModule.wasm_decrypt_record(dek, recordJson);
}

// Re-export types
export * from './types';